version: '3.1'
services:
  simple-node-app:
    image: ashish00234/node-app-3
    container: node-app-3
    ports: 
       - 3005:3000
  mongodb:
    image: mongo 
    ports:
        - 27017:27017
    environment:
       MONGO_INITDB_ROOT_USERNAME: ashish
       MONGO_INITDB_ROOT_PASSWORD: 00234

  mongo-express:
    image: mongo-express
    ports:
       - 27017:27017
    environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: ashish
       ME_CONFIG_MONGODB_ADMINPASSWORD: 00234
       ME_CONFIG_MONGODB_SERVER: mongodb

  depends_on:
     - "mongodb"

