name: ssh-key
inputs:
  ssh-key:
    required: true 
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ashish_login.pem
        chmod 600 ashish_login.pem