name: test-workflow
on: 
  workflow_call:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
       os: [ubuntu-latest] #, windows-latest, macos-latest]
       node-version: [18, 20, 22]
      # exclude:
      #   - os: [windows-latest, macos-latest]
       #    node-version: [18, 20, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-file-${{ matrix.os }}
      - uses: actions/setup-node@v5
        with:
          node-version: ${{matrix.node-version}}    
      
      